SDKS-3596 DaVinci Form Prototype
ForgeRock/ping-android-sdk pull request #22
Opened 2024-12-04 16:56 UTC by witrisna

# JIRA Ticket

Please link jira ticket here
[SDKS-3596](https://pingidentity.atlassian.net/browse/SDKS-3596)

# Description

SDKS-3596 DaVinci Form Prototype

- Require and Regex Validation
- Provide function to access ErrorNode with validation error (e.g Password policy not met)
- Handle Multi and single select collector, checkbox, dropdown, radio, combobox
- New Collectors, LABEL, SingleSelect, MultiSelect
- Handle default formData, populate default value from server.

2025-01-06 19:26 UTC, spetrov requested changes
Looks great! 👍🏻 
My comments mostly focus on readability and some english grammar suggestions...

2025-01-06 19:26 UTC, spetrov commented on davinci/CONCEPT.md
> +
Maybe this is a bit more easy to read:

_By default, the `Collector` is self-contained and does not have direct access to the `ConnectorNode`. It is responsible for handling data collection and validation specific to the field it represents. However, in certain cases, a collector may need to access the `ConnectorNode`  - for example, to retrieve global data such as the `passwordPolicy` from the root JSON to validate a password.

To enable this access, a collector can implement the `ConnectorNodeAware` interface. This interface includes the `connectorNode` property, allowing the collector to retrieve the `ConnectorNode` when needed. Once a collector is created, the `ConnectorNode` is injected into it, granting access to global data for tasks like validation or other cross-field operations._

2025-01-06 19:26 UTC, spetrov commented on davinci/CONCEPT.md
Looks great to me!
Can you please add a link to this page from the README.md? I'm not sure where exactly, but would be nice to have...

2025-01-06 19:26 UTC, spetrov commented on davinci/CONCEPT.md
> +# Design Concept
Also, a brief introduction would greatly improve the article:

_DaVinci employs a factory-based approach to dynamically create and initialize collectors for different field types in a form. This allows us to handle various field types such as text fields, password fields, and buttons, each with its own specific behavior, validation, and data collection logic._

2025-01-06 19:26 UTC, spetrov commented on davinci/CONCEPT.md
> +
Remove the empty lines at the end....

2025-01-06 19:26 UTC, spetrov commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/LabelCollector.kt
> + * This class inherits from the Collector class. It is used to display a label on the form.
`This class extends the [Collector] class.`

2025-01-06 19:26 UTC, spetrov commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/SingleSelectCollector.kt
> + * This class inherits from the FieldCollector class and implements the Collector interface.
_This class extends the [FieldCollector] class..._

2025-01-06 19:26 UTC, spetrov commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/SingleValueCollector.kt
> + * This class inherits from the FieldCollector class and implements the Collector interface.
_This class extends the [FieldCollector] class_

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/DaVinciErrorTest.kt
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/DaVinciTest.kt
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/FieldCollectorTest.kt
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/FlowCollectorTest.kt
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/LabelCollectorTest.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/MultiSelectCollectorTest.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/PasswordCollectorTest.kt
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/PasswordPolicyTest.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/TextCollectorTest.kt
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/ValidatedCollectorTest.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on samples/app/src/main/java/com/pingidentity/samples/app/AppDrawer.kt
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on samples/app/src/main/java/com/pingidentity/samples/app/Setting.kt
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on samples/app/src/main/java/com/pingidentity/samples/app/env/Env.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Update the copyright note...

2025-01-06 19:26 UTC, spetrov commented on samples/app/src/main/java/com/pingidentity/samples/app/env/EnvViewModel.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Update the copyright note...

2025-01-06 20:29 UTC, jeyanthanperiyasamy commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/Form.kt
> +
we can make it simple

is this same as above ?

json["formData"]?.jsonObject?.get("value")?.jsonObject?.let { value ->
    collectors.filterIsInstance<FieldCollector>().forEach { collector ->
        value[collector.key]?.let(collector::init)
    }
}

2025-01-07 00:25 UTC, rodrigoareis requested changes
Changes looks good to me. Minor comments to address

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/CONCEPT.md
> +
Agree with all comments above from Stoyan. Also, because it's a high level design, I believe it could easily fit in the README, avoiding the need of an additional file. However, I am ok with Stoyan's suggestion to include a link to this file. In this case, I would rename the file to something like COLLECTORS.

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/Collectors.kt
> +fun mapToJsonObject(map: Map<String, Any>): JsonObject {
Doc?

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/FieldCollector.kt
> +data class Validation(val regex: Regex, val errorMessage: String)
Doc?

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/MultiSelectCollector.kt
> +    open fun validate(): List<ValidationError> {
Doc?

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/PasswordPolicy.kt
> +data class History(
Docs?

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/SubmitCollector.kt
Update doc

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/TextCollector.kt
> +class TextCollector : ValidatedCollector()
Update doc

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/ValidatedCollector.kt
> +
remove extra line

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/main/kotlin/com/pingidentity/davinci/module/ErrorNode.kt
> +@Serializable
Docs?

2025-01-07 00:25 UTC, rodrigoareis commented on davinci/src/test/kotlin/com/pingidentity/davinci/CollectorRegistryTest.kt
> +import com.pingidentity.davinci.collector.LabelCollector
Update copyright

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/LogoutViewModel.kt
> -import com.pingidentity.samples.app.centralize.oidcClient
Update copyright

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/User.kt
> +import com.pingidentity.android.ContextProvider.context
Update copyright

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/ComboBox.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Copyright (c) 2025 Ping Identity

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/CheckBox.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Copyright (c) 2025 Ping Identity

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/Dropdown.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Copyright (c) 2025 Ping Identity

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/ErrorMessage.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Copyright (c) 2025 Ping Identity

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/Label.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Copyright (c) 2025 Ping Identity

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/Radio.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Copyright (c) 2025 Ping Identity

2025-01-07 00:25 UTC, rodrigoareis commented on samples/app/src/main/java/com/pingidentity/samples/app/env/EnvViewModel.kt
> +val test by lazy {
Can we remove those environments? We should avoid expose the details of the test environments.

2025-01-07 22:51 UTC, witrisna commented on davinci/README.md
> +```mermaid
Link included.

2025-01-07 22:54 UTC, witrisna commented on davinci/README.md
> +| FailureNode  | Unexpected Error, e.g Network, parsing ```node.cause``` to retrieve the cause of the error                |
Updated

2025-01-07 22:54 UTC, witrisna commented on davinci/README.md
> +| SuccessNode  | Authentication successful ```node.session``` to retrieve the session                                      |
Updated

2025-01-07 22:55 UTC, witrisna commented on davinci/README.md
>  For `ContinueNode` Node, you can access list of Collector with `node.collectors()` and provide input to
Updated.

2025-01-07 22:55 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/DaVinciViewModel.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Updated.

2025-01-07 22:56 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/env/Env.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Updated.

2025-01-07 22:56 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/Form.kt
> +
Updated.

2025-01-07 22:57 UTC, witrisna commented on davinci/CONCEPT.md
> +
I would keep prefer to keep it as 2 files for now, one is more for internal design which developer may not really care, and one for developer facing interface which aim for developer.

2025-01-07 22:58 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/Collectors.kt
> +fun mapToJsonObject(map: Map<String, Any>): JsonObject {
This method will be removed after DaVinci fix the dot notation.

2025-01-07 22:58 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/MultiSelectCollector.kt
> +    open fun validate(): List<ValidationError> {
Updated

2025-01-07 22:58 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/Dropdown.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Updated.

2025-01-07 22:58 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/Label.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Updated.

2025-01-07 22:58 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/Radio.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Updated.

2025-01-07 23:04 UTC, closed without merging

2025-01-07 23:04 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/env/EnvViewModel.kt
> +val test by lazy {
Updated.

2025-01-10 20:44 UTC, witrisna commented on davinci/README.md
> +textCollector.validate() //To validate the field input value with Required and Regex
Updated.

2025-01-10 20:46 UTC, witrisna commented on davinci/README.md
> +FlowCollector has the same attributes as SubmitCollector
Update entire doc with Collector

2025-01-10 20:47 UTC, witrisna commented on davinci/README.md
> +flowCollector.type == "FLOW_LINK" // Develper may want to display it as a link instead of a button.
Updated

2025-01-10 20:48 UTC, witrisna commented on davinci/README.md
> +multiSelectCollector.value.add("option1") //To set the value
Updated

2025-01-10 20:49 UTC, witrisna commented on davinci/README.md
> +| InvalidLength   | Check Password Length,  If the password length is outside this range, it adds an InvalidLength error specifying the required minimum and maximum lengths.
Updated.

2025-01-10 20:50 UTC, witrisna commented on davinci/README.md
> +| UniqueCharacter | Check for Unique Characters, If the number of unique characters is less than the required minUniqueCharacters from the policy, it adds a UniqueCharacter error with the required mi
Updated.

2025-01-10 20:52 UTC, witrisna commented on davinci/README.md
> +| MinCharacters   | Check for Character exists.
Updated, yes it does.

2025-01-10 20:54 UTC, witrisna commented on davinci/README.md
> +| Regex           | Check for valid regex.
Updated, Yes, the value will apply with the Regex, return error when pattern failed.

2025-01-10 20:57 UTC, witrisna commented on davinci/README.md
>  ### Error Handling
Updated, it is more clear with your description.

2025-01-10 20:59 UTC, witrisna commented on davinci/README.md
> +| Required        | Check for required value.
Updated.

2025-01-10 21:00 UTC, witrisna commented on davinci/CONCEPT.md
> +## How Collector map with Field Type
Updated.

2025-01-10 21:02 UTC, witrisna commented on davinci/CONCEPT.md
> +# Design Concept
Updated. The Design Concept is for the whole document, not just the mapping with field types.

2025-01-10 21:03 UTC, witrisna commented on davinci/CONCEPT.md
> +## How Collector is created & initialized
Updated.

2025-01-10 21:09 UTC, witrisna commented on davinci/CONCEPT.md
We may eventually remove the concept.md file, will leave it for now.

2025-01-10 21:10 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/LabelCollector.kt
> + * This class inherits from the Collector class. It is used to display a label on the form.
Updated.

2025-01-10 21:12 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/SingleSelectCollector.kt
> + * This class inherits from the FieldCollector class and implements the Collector interface.
Updated.

2025-01-10 21:13 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/SingleValueCollector.kt
> + * This class inherits from the FieldCollector class and implements the Collector interface.
Updated.

2025-01-10 21:13 UTC, witrisna commented on davinci/src/test/kotlin/com/pingidentity/davinci/DaVinciErrorTest.kt
Updated.

2025-01-10 21:14 UTC, witrisna commented on davinci/src/test/kotlin/com/pingidentity/davinci/FieldCollectorTest.kt
Updated.

2025-01-10 21:15 UTC, witrisna commented on davinci/src/test/kotlin/com/pingidentity/davinci/MultiSelectCollectorTest.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Updated

2025-01-10 21:16 UTC, witrisna commented on davinci/src/test/kotlin/com/pingidentity/davinci/PasswordPolicyTest.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Updated.

2025-01-10 21:16 UTC, witrisna commented on davinci/src/test/kotlin/com/pingidentity/davinci/TextCollectorTest.kt
Updated.

2025-01-10 21:16 UTC, witrisna commented on davinci/src/test/kotlin/com/pingidentity/davinci/ValidatedCollectorTest.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Updated.

2025-01-10 21:17 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/AppDrawer.kt
Updated.

2025-01-10 21:17 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/AppNavHost.kt
Updated.

2025-01-10 21:18 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/centralize/CentralizeLoginViewModel.kt
Updated.

2025-01-10 21:20 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/env/EnvViewModel.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Updated.

2025-01-10 21:23 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/SubmitCollector.kt
updated.

2025-01-10 21:24 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/TextCollector.kt
> +class TextCollector : ValidatedCollector()
Updated.

2025-01-10 21:24 UTC, witrisna commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/ValidatedCollector.kt
> +
Updated.

2025-01-10 21:27 UTC, witrisna commented on davinci/src/test/kotlin/com/pingidentity/davinci/CollectorRegistryTest.kt
> +import com.pingidentity.davinci.collector.LabelCollector
Updated.

2025-01-10 21:28 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/LogoutViewModel.kt
> -import com.pingidentity.samples.app.centralize.oidcClient
Updated.

2025-01-10 21:28 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/User.kt
> +import com.pingidentity.android.ContextProvider.context
Updated.

2025-01-10 21:28 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/CheckBox.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Updated.

2025-01-10 21:28 UTC, witrisna commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/ComboBox.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Updated

2025-01-10 22:56 UTC, spetrov commented on davinci/CONCEPT.md
> +## How Collector populate default value
This has been updated.

2025-01-10 22:56 UTC, spetrov commented on davinci/CONCEPT.md
> +## How Collector access ConnectorNode
This has been updated.

2025-01-10 22:57 UTC, spetrov commented on davinci/CONCEPT.md
> +
This has been updated.

2025-01-10 23:00 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/FlowCollectorTest.kt
This has been updated.

2025-01-10 23:01 UTC, spetrov commented on davinci/src/test/kotlin/com/pingidentity/davinci/LabelCollectorTest.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Updated

2025-01-10 23:03 UTC, spetrov commented on samples/app/src/main/java/com/pingidentity/samples/app/Setting.kt
Updated

2025-01-10 23:03 UTC, spetrov commented on samples/app/src/main/java/com/pingidentity/samples/app/Setting.kt
> + * Copyright (c) 2024 Ping Identity. All rights reserved.
Updated

2025-01-10 23:05 UTC, spetrov commented on davinci/src/main/kotlin/com/pingidentity/davinci/collector/FieldCollector.kt
> +data class Validation(val regex: Regex, val errorMessage: String)
This has been addressed

2025-01-10 23:13 UTC, spetrov commented on samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/ErrorMessage.kt
> + * Copyright (c) 2024 - 2025 Ping Identity. All rights reserved.
Updated